export const DOCUMENT_MAXIMUM_FILE_SIZE_BYTES = 10 * 1024 * 1024;
export const DOCUMENT_APPROVED_DEIDENTIFIED_TEXT_MAX_LENGTH = 100000;
export const DOCUMENT_REVIEWED_SUMMARY_MAX_LENGTH = 10000;
export const DOCUMENT_HISTORY_TITLE_MAX_LENGTH = 200;
